/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "src/project.v:12.1-156.10" *)
module tt_um_BNN(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  (* src = "src/project.v:59.16-59.32" *)
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  (* src = "src/project.v:36.5-36.14" *)
  wire _0545_;
  (* src = "src/project.v:18.23-18.26" *)
  wire _0546_;
  (* src = "src/project.v:32.11-32.21" *)
  wire _0547_;
  (* src = "src/project.v:32.11-32.21" *)
  wire _0548_;
  (* src = "src/project.v:32.11-32.21" *)
  wire _0549_;
  (* src = "src/project.v:32.11-32.21" *)
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  wire _0799_;
  wire _0800_;
  wire _0801_;
  wire _0802_;
  wire _0803_;
  wire _0804_;
  wire _0805_;
  wire _0806_;
  wire _0807_;
  wire _0808_;
  wire _0809_;
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  wire _0815_;
  wire _0816_;
  wire _0817_;
  (* src = "src/project.v:35.11-35.22" *)
  wire _0818_;
  (* src = "src/project.v:35.11-35.22" *)
  wire _0819_;
  (* src = "src/project.v:35.11-35.22" *)
  wire _0820_;
  (* src = "src/project.v:35.11-35.22" *)
  wire _0821_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0822_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0823_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0824_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0825_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0826_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0827_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0828_;
  (* src = "src/project.v:13.23-13.28" *)
  wire _0829_;
  (* src = "src/project.v:15.23-15.29" *)
  wire _0830_;
  (* src = "src/project.v:15.23-15.29" *)
  wire _0831_;
  (* src = "src/project.v:15.23-15.29" *)
  wire _0832_;
  (* src = "src/project.v:15.23-15.29" *)
  wire _0833_;
  (* src = "src/project.v:15.23-15.29" *)
  wire _0834_;
  (* src = "src/project.v:14.23-14.29" *)
  wire _0835_;
  (* src = "src/project.v:14.23-14.29" *)
  wire _0836_;
  (* src = "src/project.v:14.23-14.29" *)
  wire _0837_;
  (* src = "src/project.v:14.23-14.29" *)
  wire _0838_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0839_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0840_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0841_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0842_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0843_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0844_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0845_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0846_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0847_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0848_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0849_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0850_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0851_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0852_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0853_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0854_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0855_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0856_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0857_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0858_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0859_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0860_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0861_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0862_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0863_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0864_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0865_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0866_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0867_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0868_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0869_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0870_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0871_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0872_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0873_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0874_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0875_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0876_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0877_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0878_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0879_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0880_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0881_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0882_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0883_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0884_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0885_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0886_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0887_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0888_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0889_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0890_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0891_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0892_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0893_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0894_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0895_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0896_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0897_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0898_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0899_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0900_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0901_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0902_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0903_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0904_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0905_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0906_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0907_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0908_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0909_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0910_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0911_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0912_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0913_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0914_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0915_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0916_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0917_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0918_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0919_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0920_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0921_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0922_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0923_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0924_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0925_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0926_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0927_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0928_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0929_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0930_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0931_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0932_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0933_;
  (* src = "src/project.v:30.25-30.32" *)
  wire _0934_;
  (* force_downto = 32'd1 *)
  (* src = "src/project.v:65.21-65.35|/opt/homebrew/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "4" *)
  wire [4:0] _0935_;
  (* force_downto = 32'd1 *)
  (* src = "src/project.v:65.21-65.35|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [4:0] _0936_;
  wire _0937_;
  wire _0938_;
  wire _0939_;
  wire _0940_;
  wire _0941_;
  wire _0942_;
  wire _0943_;
  wire _0944_;
  wire _0945_;
  wire _0946_;
  wire _0947_;
  wire _0948_;
  wire _0949_;
  wire _0950_;
  wire _0951_;
  wire _0952_;
  wire _0953_;
  wire _0954_;
  wire _0955_;
  wire _0956_;
  wire _0957_;
  wire _0958_;
  wire _0959_;
  wire _0960_;
  wire _0961_;
  wire _0962_;
  wire _0963_;
  wire _0964_;
  wire _0965_;
  wire _0966_;
  wire _0967_;
  wire _0968_;
  wire _0969_;
  wire _0970_;
  wire _0971_;
  wire _0972_;
  wire _0973_;
  wire _0974_;
  wire _0975_;
  wire _0976_;
  wire _0977_;
  wire _0978_;
  wire _0979_;
  wire _0980_;
  wire _0981_;
  wire _0982_;
  wire _0983_;
  wire _0984_;
  wire _0985_;
  wire _0986_;
  wire _0987_;
  wire _0988_;
  wire _0989_;
  wire _0990_;
  wire _0991_;
  wire _0992_;
  wire _0993_;
  wire _0994_;
  wire _0995_;
  wire _0996_;
  wire _0997_;
  wire _0998_;
  wire _0999_;
  wire _1000_;
  wire _1001_;
  wire _1002_;
  wire _1003_;
  wire _1004_;
  wire _1005_;
  wire _1006_;
  wire _1007_;
  wire _1008_;
  wire _1009_;
  wire _1010_;
  wire _1011_;
  wire _1012_;
  wire _1013_;
  wire _1014_;
  wire _1015_;
  wire _1016_;
  wire _1017_;
  wire _1018_;
  wire _1019_;
  wire _1020_;
  wire _1021_;
  wire _1022_;
  wire _1023_;
  wire _1024_;
  wire _1025_;
  wire _1026_;
  wire _1027_;
  wire _1028_;
  wire _1029_;
  wire _1030_;
  wire _1031_;
  wire _1032_;
  wire _1033_;
  wire _1034_;
  wire _1035_;
  wire _1036_;
  wire _1037_;
  wire _1038_;
  wire _1039_;
  wire _1040_;
  wire _1041_;
  (* src = "src/project.v:36.5-36.14" *)
  wire bit_index;
  (* src = "src/project.v:19.23-19.26" *)
  input clk;
  wire clk;
  (* src = "src/project.v:18.23-18.26" *)
  input ena;
  wire ena;
  (* src = "src/project.v:32.11-32.21" *)
  (* unused_bits = "4" *)
  wire [4:0] load_state;
  (* src = "src/project.v:141.12-141.23" *)
  wire [3:0] neuron_out3;
  (* src = "src/project.v:20.23-20.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/project.v:35.11-35.22" *)
  wire [3:0] temp_weight;
  (* src = "src/project.v:13.23-13.28" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "src/project.v:15.23-15.29" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "src/project.v:17.23-17.29" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "src/project.v:16.23-16.30" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "src/project.v:14.23-14.29" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[0] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[10] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[11] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[1] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[2] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[3] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[4] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[5] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[6] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[7] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[8] ;
  (* src = "src/project.v:30.25-30.32" *)
  wire [7:0] \weights[9] ;
  sky130_fd_sc_hd__xnor2_1 _1042_ (
    .A(_0840_),
    .B(_0823_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__xor2_1 _1043_ (
    .A(_0839_),
    .B(_0822_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__clkinv_1 _1044_ (
    .A(_0552_),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__xnor2_1 _1045_ (
    .A(_0842_),
    .B(_0825_),
    .Y(_0554_)
  );
  sky130_fd_sc_hd__maj3_1 _1046_ (
    .A(_0551_),
    .B(_0553_),
    .C(_0554_),
    .X(_0555_)
  );
  sky130_fd_sc_hd__xnor3_1 _1047_ (
    .A(_0551_),
    .B(_0552_),
    .C(_0554_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__xnor2_1 _1048_ (
    .A(_0845_),
    .B(_0828_),
    .Y(_0557_)
  );
  sky130_fd_sc_hd__xnor2_1 _1049_ (
    .A(_0844_),
    .B(_0827_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__xor3_1 _1050_ (
    .A(_0556_),
    .B(_0557_),
    .C(_0558_),
    .X(_0559_)
  );
  sky130_fd_sc_hd__xnor2_1 _1051_ (
    .A(_0843_),
    .B(_0826_),
    .Y(_0560_)
  );
  sky130_fd_sc_hd__xnor2_1 _1052_ (
    .A(_0846_),
    .B(_0829_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__xnor2_1 _1053_ (
    .A(_0841_),
    .B(_0824_),
    .Y(_0562_)
  );
  sky130_fd_sc_hd__xor3_1 _1054_ (
    .A(_0559_),
    .B(_0560_),
    .C(_0561_),
    .X(_0563_)
  );
  sky130_fd_sc_hd__maj3_1 _1055_ (
    .A(_0556_),
    .B(_0557_),
    .C(_0558_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__maj3_1 _1056_ (
    .A(_0559_),
    .B(_0560_),
    .C(_0561_),
    .X(_0565_)
  );
  sky130_fd_sc_hd__a221oi_1 _1057_ (
    .A1(_0562_),
    .A2(_0563_),
    .B1(_0564_),
    .B2(_0565_),
    .C1(_0555_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__a311oi_1 _1058_ (
    .A1(_0555_),
    .A2(_0562_),
    .A3(_0563_),
    .B1(_0564_),
    .C1(_0565_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__nor2_1 _1059_ (
    .A(_0566_),
    .B(_0567_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__xor2_1 _1060_ (
    .A(_0919_),
    .B(_0568_),
    .X(_0569_)
  );
  sky130_fd_sc_hd__xor2_1 _1061_ (
    .A(_0823_),
    .B(_0864_),
    .X(_0570_)
  );
  sky130_fd_sc_hd__xor2_1 _1062_ (
    .A(_0822_),
    .B(_0863_),
    .X(_0571_)
  );
  sky130_fd_sc_hd__nor2_1 _1063_ (
    .A(_0570_),
    .B(_0571_),
    .Y(_0572_)
  );
  sky130_fd_sc_hd__nand2_1 _1064_ (
    .A(_0570_),
    .B(_0571_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__xnor2_1 _1065_ (
    .A(_0825_),
    .B(_0866_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__xnor3_1 _1066_ (
    .A(_0570_),
    .B(_0571_),
    .C(_0574_),
    .X(_0575_)
  );
  sky130_fd_sc_hd__xor2_1 _1067_ (
    .A(_0828_),
    .B(_0869_),
    .X(_0576_)
  );
  sky130_fd_sc_hd__xor2_1 _1068_ (
    .A(_0827_),
    .B(_0868_),
    .X(_0577_)
  );
  sky130_fd_sc_hd__maj3_1 _1069_ (
    .A(_0575_),
    .B(_0576_),
    .C(_0577_),
    .X(_0578_)
  );
  sky130_fd_sc_hd__a21oi_1 _1070_ (
    .A1(_0573_),
    .A2(_0574_),
    .B1(_0572_),
    .Y(_0579_)
  );
  sky130_fd_sc_hd__nand2_1 _1071_ (
    .A(_0578_),
    .B(_0579_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__xor3_1 _1072_ (
    .A(_0575_),
    .B(_0576_),
    .C(_0577_),
    .X(_0581_)
  );
  sky130_fd_sc_hd__xor2_1 _1073_ (
    .A(_0826_),
    .B(_0867_),
    .X(_0582_)
  );
  sky130_fd_sc_hd__nor2_1 _1074_ (
    .A(_0581_),
    .B(_0582_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__xor2_1 _1075_ (
    .A(_0581_),
    .B(_0582_),
    .X(_0584_)
  );
  sky130_fd_sc_hd__xnor2_1 _1076_ (
    .A(_0829_),
    .B(_0870_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__nor2_1 _1077_ (
    .A(_0578_),
    .B(_0579_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__a211o_1 _1078_ (
    .A1(_0584_),
    .A2(_0585_),
    .B1(_0586_),
    .C1(_0583_),
    .X(_0587_)
  );
  sky130_fd_sc_hd__xnor2_1 _1079_ (
    .A(_0824_),
    .B(_0865_),
    .Y(_0588_)
  );
  sky130_fd_sc_hd__xor2_1 _1080_ (
    .A(_0578_),
    .B(_0579_),
    .X(_0589_)
  );
  sky130_fd_sc_hd__xnor2_1 _1081_ (
    .A(_0584_),
    .B(_0585_),
    .Y(_0590_)
  );
  sky130_fd_sc_hd__o21ai_0 _1082_ (
    .A1(_0583_),
    .A2(_0589_),
    .B1(_0588_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _1083_ (
    .A1_N(_0580_),
    .A2_N(_0587_),
    .B1(_0590_),
    .B2(_0591_),
    .Y(_0592_)
  );
  sky130_fd_sc_hd__xnor2_1 _1084_ (
    .A(_0920_),
    .B(_0592_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__clkinv_1 _1085_ (
    .A(_0593_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nor2_1 _1086_ (
    .A(_0569_),
    .B(_0594_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__nand2_1 _1087_ (
    .A(_0569_),
    .B(_0594_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__xnor2_1 _1088_ (
    .A(_0824_),
    .B(_0881_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__xor2_1 _1089_ (
    .A(_0823_),
    .B(_0880_),
    .X(_0598_)
  );
  sky130_fd_sc_hd__xor2_1 _1090_ (
    .A(_0822_),
    .B(_0879_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__nor2_1 _1091_ (
    .A(_0598_),
    .B(_0599_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__nand2_1 _1092_ (
    .A(_0598_),
    .B(_0599_),
    .Y(_0601_)
  );
  sky130_fd_sc_hd__xnor2_1 _1093_ (
    .A(_0825_),
    .B(_0882_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__xor3_1 _1094_ (
    .A(_0598_),
    .B(_0599_),
    .C(_0602_),
    .X(_0603_)
  );
  sky130_fd_sc_hd__xnor2_1 _1095_ (
    .A(_0828_),
    .B(_0885_),
    .Y(_0604_)
  );
  sky130_fd_sc_hd__xnor2_1 _1096_ (
    .A(_0827_),
    .B(_0884_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__xnor3_1 _1097_ (
    .A(_0603_),
    .B(_0604_),
    .C(_0605_),
    .X(_0606_)
  );
  sky130_fd_sc_hd__xor2_1 _1098_ (
    .A(_0826_),
    .B(_0883_),
    .X(_0607_)
  );
  sky130_fd_sc_hd__nor2_1 _1099_ (
    .A(_0606_),
    .B(_0607_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__xor2_1 _1100_ (
    .A(_0606_),
    .B(_0607_),
    .X(_0609_)
  );
  sky130_fd_sc_hd__xnor2_1 _1101_ (
    .A(_0829_),
    .B(_0886_),
    .Y(_0610_)
  );
  sky130_fd_sc_hd__maj3_1 _1102_ (
    .A(_0603_),
    .B(_0604_),
    .C(_0605_),
    .X(_0611_)
  );
  sky130_fd_sc_hd__a21oi_1 _1103_ (
    .A1(_0601_),
    .A2(_0602_),
    .B1(_0600_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1104_ (
    .A(_0611_),
    .SLEEP(_0612_),
    .X(_0613_)
  );
  sky130_fd_sc_hd__nor2b_1 _1105_ (
    .A(_0611_),
    .B_N(_0612_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__xnor2_1 _1106_ (
    .A(_0611_),
    .B(_0612_),
    .Y(_0615_)
  );
  sky130_fd_sc_hd__o21ai_0 _1107_ (
    .A1(_0608_),
    .A2(_0615_),
    .B1(_0597_),
    .Y(_0616_)
  );
  sky130_fd_sc_hd__xnor2_1 _1108_ (
    .A(_0609_),
    .B(_0610_),
    .Y(_0617_)
  );
  sky130_fd_sc_hd__a211oi_1 _1109_ (
    .A1(_0609_),
    .A2(_0610_),
    .B1(_0613_),
    .C1(_0608_),
    .Y(_0618_)
  );
  sky130_fd_sc_hd__o22ai_1 _1110_ (
    .A1(_0616_),
    .A2(_0617_),
    .B1(_0618_),
    .B2(_0614_),
    .Y(_0619_)
  );
  sky130_fd_sc_hd__xnor2_1 _1111_ (
    .A(_0922_),
    .B(_0619_),
    .Y(_0620_)
  );
  sky130_fd_sc_hd__xnor3_1 _1112_ (
    .A(_0569_),
    .B(_0593_),
    .C(_0620_),
    .X(_0621_)
  );
  sky130_fd_sc_hd__xor2_1 _1113_ (
    .A(_0823_),
    .B(_0904_),
    .X(_0622_)
  );
  sky130_fd_sc_hd__xor2_1 _1114_ (
    .A(_0822_),
    .B(_0903_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__nor2_1 _1115_ (
    .A(_0622_),
    .B(_0623_),
    .Y(_0624_)
  );
  sky130_fd_sc_hd__nand2_1 _1116_ (
    .A(_0622_),
    .B(_0623_),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__xnor2_1 _1117_ (
    .A(_0825_),
    .B(_0906_),
    .Y(_0626_)
  );
  sky130_fd_sc_hd__xnor3_1 _1118_ (
    .A(_0622_),
    .B(_0623_),
    .C(_0626_),
    .X(_0627_)
  );
  sky130_fd_sc_hd__xor2_1 _1119_ (
    .A(_0828_),
    .B(_0909_),
    .X(_0628_)
  );
  sky130_fd_sc_hd__nor2_1 _1120_ (
    .A(_0627_),
    .B(_0628_),
    .Y(_0629_)
  );
  sky130_fd_sc_hd__nand2_1 _1121_ (
    .A(_0627_),
    .B(_0628_),
    .Y(_0630_)
  );
  sky130_fd_sc_hd__xnor2_1 _1122_ (
    .A(_0827_),
    .B(_0908_),
    .Y(_0631_)
  );
  sky130_fd_sc_hd__a21o_1 _1123_ (
    .A1(_0630_),
    .A2(_0631_),
    .B1(_0629_),
    .X(_0632_)
  );
  sky130_fd_sc_hd__xor3_1 _1124_ (
    .A(_0627_),
    .B(_0628_),
    .C(_0631_),
    .X(_0633_)
  );
  sky130_fd_sc_hd__xnor2_1 _1125_ (
    .A(_0826_),
    .B(_0907_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__xnor2_1 _1126_ (
    .A(_0633_),
    .B(_0634_),
    .Y(_0635_)
  );
  sky130_fd_sc_hd__xnor2_1 _1127_ (
    .A(_0829_),
    .B(_0910_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__maj3_1 _1128_ (
    .A(_0633_),
    .B(_0634_),
    .C(_0636_),
    .X(_0637_)
  );
  sky130_fd_sc_hd__xnor2_1 _1129_ (
    .A(_0824_),
    .B(_0905_),
    .Y(_0638_)
  );
  sky130_fd_sc_hd__xnor2_1 _1130_ (
    .A(_0635_),
    .B(_0636_),
    .Y(_0639_)
  );
  sky130_fd_sc_hd__a21o_1 _1131_ (
    .A1(_0625_),
    .A2(_0626_),
    .B1(_0624_),
    .X(_0640_)
  );
  sky130_fd_sc_hd__a221oi_1 _1132_ (
    .A1(_0632_),
    .A2(_0637_),
    .B1(_0638_),
    .B2(_0639_),
    .C1(_0640_),
    .Y(_0641_)
  );
  sky130_fd_sc_hd__a311oi_1 _1133_ (
    .A1(_0638_),
    .A2(_0639_),
    .A3(_0640_),
    .B1(_0637_),
    .C1(_0632_),
    .Y(_0642_)
  );
  sky130_fd_sc_hd__nor2_1 _1134_ (
    .A(_0641_),
    .B(_0642_),
    .Y(_0643_)
  );
  sky130_fd_sc_hd__xnor2_1 _1135_ (
    .A(_0925_),
    .B(_0643_),
    .Y(_0644_)
  );
  sky130_fd_sc_hd__xnor2_1 _1136_ (
    .A(_0823_),
    .B(_0896_),
    .Y(_0645_)
  );
  sky130_fd_sc_hd__xnor2_1 _1137_ (
    .A(_0822_),
    .B(_0895_),
    .Y(_0646_)
  );
  sky130_fd_sc_hd__xnor2_1 _1138_ (
    .A(_0825_),
    .B(_0898_),
    .Y(_0647_)
  );
  sky130_fd_sc_hd__xnor3_1 _1139_ (
    .A(_0645_),
    .B(_0646_),
    .C(_0647_),
    .X(_0648_)
  );
  sky130_fd_sc_hd__xor2_1 _1140_ (
    .A(_0828_),
    .B(_0901_),
    .X(_0649_)
  );
  sky130_fd_sc_hd__nor2_1 _1141_ (
    .A(_0648_),
    .B(_0649_),
    .Y(_0650_)
  );
  sky130_fd_sc_hd__nand2_1 _1142_ (
    .A(_0648_),
    .B(_0649_),
    .Y(_0651_)
  );
  sky130_fd_sc_hd__xnor2_1 _1143_ (
    .A(_0827_),
    .B(_0900_),
    .Y(_0652_)
  );
  sky130_fd_sc_hd__a21o_1 _1144_ (
    .A1(_0651_),
    .A2(_0652_),
    .B1(_0650_),
    .X(_0653_)
  );
  sky130_fd_sc_hd__xor3_1 _1145_ (
    .A(_0648_),
    .B(_0649_),
    .C(_0652_),
    .X(_0654_)
  );
  sky130_fd_sc_hd__xnor2_1 _1146_ (
    .A(_0826_),
    .B(_0899_),
    .Y(_0655_)
  );
  sky130_fd_sc_hd__xnor2_1 _1147_ (
    .A(_0654_),
    .B(_0655_),
    .Y(_0656_)
  );
  sky130_fd_sc_hd__xnor2_1 _1148_ (
    .A(_0829_),
    .B(_0902_),
    .Y(_0657_)
  );
  sky130_fd_sc_hd__maj3_1 _1149_ (
    .A(_0654_),
    .B(_0655_),
    .C(_0657_),
    .X(_0658_)
  );
  sky130_fd_sc_hd__xnor2_1 _1150_ (
    .A(_0824_),
    .B(_0897_),
    .Y(_0659_)
  );
  sky130_fd_sc_hd__xnor2_1 _1151_ (
    .A(_0656_),
    .B(_0657_),
    .Y(_0660_)
  );
  sky130_fd_sc_hd__maj3_1 _1152_ (
    .A(_0645_),
    .B(_0646_),
    .C(_0647_),
    .X(_0661_)
  );
  sky130_fd_sc_hd__a221oi_1 _1153_ (
    .A1(_0653_),
    .A2(_0658_),
    .B1(_0659_),
    .B2(_0660_),
    .C1(_0661_),
    .Y(_0662_)
  );
  sky130_fd_sc_hd__a311oi_1 _1154_ (
    .A1(_0659_),
    .A2(_0660_),
    .A3(_0661_),
    .B1(_0658_),
    .C1(_0653_),
    .Y(_0663_)
  );
  sky130_fd_sc_hd__nor2_1 _1155_ (
    .A(_0662_),
    .B(_0663_),
    .Y(_0664_)
  );
  sky130_fd_sc_hd__xnor2_1 _1156_ (
    .A(_0924_),
    .B(_0664_),
    .Y(_0665_)
  );
  sky130_fd_sc_hd__maj3_1 _1157_ (
    .A(_0621_),
    .B(_0644_),
    .C(_0665_),
    .X(_0666_)
  );
  sky130_fd_sc_hd__xnor3_1 _1158_ (
    .A(_0621_),
    .B(_0644_),
    .C(_0665_),
    .X(_0667_)
  );
  sky130_fd_sc_hd__xnor2_1 _1159_ (
    .A(_0823_),
    .B(_0888_),
    .Y(_0668_)
  );
  sky130_fd_sc_hd__xnor2_1 _1160_ (
    .A(_0822_),
    .B(_0887_),
    .Y(_0669_)
  );
  sky130_fd_sc_hd__xnor2_1 _1161_ (
    .A(_0668_),
    .B(_0669_),
    .Y(_0670_)
  );
  sky130_fd_sc_hd__xnor2_1 _1162_ (
    .A(_0825_),
    .B(_0890_),
    .Y(_0671_)
  );
  sky130_fd_sc_hd__xnor2_1 _1163_ (
    .A(_0670_),
    .B(_0671_),
    .Y(_0672_)
  );
  sky130_fd_sc_hd__xnor2_1 _1164_ (
    .A(_0828_),
    .B(_0893_),
    .Y(_0673_)
  );
  sky130_fd_sc_hd__xnor2_1 _1165_ (
    .A(_0827_),
    .B(_0892_),
    .Y(_0674_)
  );
  sky130_fd_sc_hd__maj3_1 _1166_ (
    .A(_0672_),
    .B(_0673_),
    .C(_0674_),
    .X(_0675_)
  );
  sky130_fd_sc_hd__xor3_1 _1167_ (
    .A(_0672_),
    .B(_0673_),
    .C(_0674_),
    .X(_0676_)
  );
  sky130_fd_sc_hd__xnor2_1 _1168_ (
    .A(_0826_),
    .B(_0891_),
    .Y(_0677_)
  );
  sky130_fd_sc_hd__xnor2_1 _1169_ (
    .A(_0676_),
    .B(_0677_),
    .Y(_0678_)
  );
  sky130_fd_sc_hd__xnor2_1 _1170_ (
    .A(_0829_),
    .B(_0894_),
    .Y(_0679_)
  );
  sky130_fd_sc_hd__maj3_1 _1171_ (
    .A(_0676_),
    .B(_0677_),
    .C(_0679_),
    .X(_0680_)
  );
  sky130_fd_sc_hd__xnor2_1 _1172_ (
    .A(_0824_),
    .B(_0889_),
    .Y(_0681_)
  );
  sky130_fd_sc_hd__xnor2_1 _1173_ (
    .A(_0678_),
    .B(_0679_),
    .Y(_0682_)
  );
  sky130_fd_sc_hd__maj3_1 _1174_ (
    .A(_0668_),
    .B(_0669_),
    .C(_0671_),
    .X(_0683_)
  );
  sky130_fd_sc_hd__a221oi_1 _1175_ (
    .A1(_0675_),
    .A2(_0680_),
    .B1(_0681_),
    .B2(_0682_),
    .C1(_0683_),
    .Y(_0684_)
  );
  sky130_fd_sc_hd__a311oi_1 _1176_ (
    .A1(_0681_),
    .A2(_0682_),
    .A3(_0683_),
    .B1(_0680_),
    .C1(_0675_),
    .Y(_0685_)
  );
  sky130_fd_sc_hd__nor2_1 _1177_ (
    .A(_0684_),
    .B(_0685_),
    .Y(_0686_)
  );
  sky130_fd_sc_hd__xor2_1 _1178_ (
    .A(_0923_),
    .B(_0686_),
    .X(_0687_)
  );
  sky130_fd_sc_hd__xnor2_1 _1179_ (
    .A(_0823_),
    .B(_0912_),
    .Y(_0688_)
  );
  sky130_fd_sc_hd__xnor2_1 _1180_ (
    .A(_0822_),
    .B(_0911_),
    .Y(_0689_)
  );
  sky130_fd_sc_hd__xnor2_1 _1181_ (
    .A(_0825_),
    .B(_0914_),
    .Y(_0690_)
  );
  sky130_fd_sc_hd__xnor3_1 _1182_ (
    .A(_0688_),
    .B(_0689_),
    .C(_0690_),
    .X(_0691_)
  );
  sky130_fd_sc_hd__xor2_1 _1183_ (
    .A(_0828_),
    .B(_0917_),
    .X(_0692_)
  );
  sky130_fd_sc_hd__nor2_1 _1184_ (
    .A(_0691_),
    .B(_0692_),
    .Y(_0693_)
  );
  sky130_fd_sc_hd__nand2_1 _1185_ (
    .A(_0691_),
    .B(_0692_),
    .Y(_0694_)
  );
  sky130_fd_sc_hd__xnor2_1 _1186_ (
    .A(_0827_),
    .B(_0916_),
    .Y(_0695_)
  );
  sky130_fd_sc_hd__xor3_1 _1187_ (
    .A(_0691_),
    .B(_0692_),
    .C(_0695_),
    .X(_0696_)
  );
  sky130_fd_sc_hd__xnor2_1 _1188_ (
    .A(_0826_),
    .B(_0915_),
    .Y(_0697_)
  );
  sky130_fd_sc_hd__xor2_1 _1189_ (
    .A(_0696_),
    .B(_0697_),
    .X(_0698_)
  );
  sky130_fd_sc_hd__xnor2_1 _1190_ (
    .A(_0829_),
    .B(_0918_),
    .Y(_0699_)
  );
  sky130_fd_sc_hd__xor2_1 _1191_ (
    .A(_0824_),
    .B(_0913_),
    .X(_0700_)
  );
  sky130_fd_sc_hd__xnor2_1 _1192_ (
    .A(_0698_),
    .B(_0699_),
    .Y(_0701_)
  );
  sky130_fd_sc_hd__nor2_1 _1193_ (
    .A(_0700_),
    .B(_0701_),
    .Y(_0702_)
  );
  sky130_fd_sc_hd__a21o_1 _1194_ (
    .A1(_0694_),
    .A2(_0695_),
    .B1(_0693_),
    .X(_0703_)
  );
  sky130_fd_sc_hd__maj3_1 _1195_ (
    .A(_0688_),
    .B(_0689_),
    .C(_0690_),
    .X(_0704_)
  );
  sky130_fd_sc_hd__maj3_1 _1196_ (
    .A(_0696_),
    .B(_0697_),
    .C(_0699_),
    .X(_0705_)
  );
  sky130_fd_sc_hd__a211oi_1 _1197_ (
    .A1(_0704_),
    .A2(_0705_),
    .B1(_0702_),
    .C1(_0703_),
    .Y(_0706_)
  );
  sky130_fd_sc_hd__a211oi_1 _1198_ (
    .A1(_0702_),
    .A2(_0703_),
    .B1(_0704_),
    .C1(_0705_),
    .Y(_0707_)
  );
  sky130_fd_sc_hd__nor2_1 _1199_ (
    .A(_0706_),
    .B(_0707_),
    .Y(_0708_)
  );
  sky130_fd_sc_hd__xor2_1 _1200_ (
    .A(_0926_),
    .B(_0708_),
    .X(_0709_)
  );
  sky130_fd_sc_hd__xnor2_1 _1201_ (
    .A(_0823_),
    .B(_0872_),
    .Y(_0710_)
  );
  sky130_fd_sc_hd__xnor2_1 _1202_ (
    .A(_0822_),
    .B(_0871_),
    .Y(_0711_)
  );
  sky130_fd_sc_hd__nand2_1 _1203_ (
    .A(_0710_),
    .B(_0711_),
    .Y(_0712_)
  );
  sky130_fd_sc_hd__xor2_1 _1204_ (
    .A(_0710_),
    .B(_0711_),
    .X(_0713_)
  );
  sky130_fd_sc_hd__xnor2_1 _1205_ (
    .A(_0825_),
    .B(_0874_),
    .Y(_0714_)
  );
  sky130_fd_sc_hd__nand2_1 _1206_ (
    .A(_0713_),
    .B(_0714_),
    .Y(_0715_)
  );
  sky130_fd_sc_hd__xor2_1 _1207_ (
    .A(_0713_),
    .B(_0714_),
    .X(_0716_)
  );
  sky130_fd_sc_hd__xnor2_1 _1208_ (
    .A(_0828_),
    .B(_0877_),
    .Y(_0717_)
  );
  sky130_fd_sc_hd__nand2_1 _1209_ (
    .A(_0716_),
    .B(_0717_),
    .Y(_0718_)
  );
  sky130_fd_sc_hd__xor2_1 _1210_ (
    .A(_0716_),
    .B(_0717_),
    .X(_0719_)
  );
  sky130_fd_sc_hd__xnor2_1 _1211_ (
    .A(_0827_),
    .B(_0876_),
    .Y(_0720_)
  );
  sky130_fd_sc_hd__nand2_1 _1212_ (
    .A(_0719_),
    .B(_0720_),
    .Y(_0721_)
  );
  sky130_fd_sc_hd__nand4_1 _1213_ (
    .A(_0712_),
    .B(_0715_),
    .C(_0718_),
    .D(_0721_),
    .Y(_0722_)
  );
  sky130_fd_sc_hd__xnor2_1 _1214_ (
    .A(_0719_),
    .B(_0720_),
    .Y(_0723_)
  );
  sky130_fd_sc_hd__xnor2_1 _1215_ (
    .A(_0826_),
    .B(_0875_),
    .Y(_0724_)
  );
  sky130_fd_sc_hd__nor2b_1 _1216_ (
    .A(_0723_),
    .B_N(_0724_),
    .Y(_0725_)
  );
  sky130_fd_sc_hd__xor2_1 _1217_ (
    .A(_0723_),
    .B(_0724_),
    .X(_0726_)
  );
  sky130_fd_sc_hd__xor2_1 _1218_ (
    .A(_0829_),
    .B(_0878_),
    .X(_0727_)
  );
  sky130_fd_sc_hd__nor2_1 _1219_ (
    .A(_0726_),
    .B(_0727_),
    .Y(_0728_)
  );
  sky130_fd_sc_hd__a22oi_1 _1220_ (
    .A1(_0712_),
    .A2(_0715_),
    .B1(_0718_),
    .B2(_0721_),
    .Y(_0729_)
  );
  sky130_fd_sc_hd__o31ai_1 _1221_ (
    .A1(_0725_),
    .A2(_0728_),
    .A3(_0729_),
    .B1(_0722_),
    .Y(_0730_)
  );
  sky130_fd_sc_hd__xnor2_1 _1222_ (
    .A(_0824_),
    .B(_0873_),
    .Y(_0731_)
  );
  sky130_fd_sc_hd__and2_0 _1223_ (
    .A(_0726_),
    .B(_0727_),
    .X(_0732_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _1224_ (
    .A(_0722_),
    .SLEEP(_0729_),
    .X(_0733_)
  );
  sky130_fd_sc_hd__o21ai_0 _1225_ (
    .A1(_0725_),
    .A2(_0733_),
    .B1(_0731_),
    .Y(_0734_)
  );
  sky130_fd_sc_hd__o31ai_1 _1226_ (
    .A1(_0728_),
    .A2(_0732_),
    .A3(_0734_),
    .B1(_0730_),
    .Y(_0735_)
  );
  sky130_fd_sc_hd__xor2_1 _1227_ (
    .A(_0921_),
    .B(_0735_),
    .X(_0736_)
  );
  sky130_fd_sc_hd__xor3_1 _1228_ (
    .A(_0667_),
    .B(_0687_),
    .C(_0709_),
    .X(_0737_)
  );
  sky130_fd_sc_hd__a21oi_1 _1229_ (
    .A1(_0596_),
    .A2(_0620_),
    .B1(_0595_),
    .Y(_0738_)
  );
  sky130_fd_sc_hd__maj3_1 _1230_ (
    .A(_0667_),
    .B(_0687_),
    .C(_0709_),
    .X(_0739_)
  );
  sky130_fd_sc_hd__nand2_1 _1231_ (
    .A(_0738_),
    .B(_0739_),
    .Y(_0740_)
  );
  sky130_fd_sc_hd__o211ai_1 _1232_ (
    .A1(_0736_),
    .A2(_0737_),
    .B1(_0738_),
    .C1(_0739_),
    .Y(_0741_)
  );
  sky130_fd_sc_hd__o22ai_1 _1233_ (
    .A1(_0736_),
    .A2(_0737_),
    .B1(_0738_),
    .B2(_0739_),
    .Y(_0742_)
  );
  sky130_fd_sc_hd__a22o_1 _1234_ (
    .A1(_0666_),
    .A2(_0741_),
    .B1(_0742_),
    .B2(_0740_),
    .X(_0835_)
  );
  sky130_fd_sc_hd__xnor2_1 _1235_ (
    .A(_0927_),
    .B(_0568_),
    .Y(_0743_)
  );
  sky130_fd_sc_hd__xnor2_1 _1236_ (
    .A(_0928_),
    .B(_0592_),
    .Y(_0744_)
  );
  sky130_fd_sc_hd__xnor2_1 _1237_ (
    .A(_0930_),
    .B(_0619_),
    .Y(_0745_)
  );
  sky130_fd_sc_hd__xor3_1 _1238_ (
    .A(_0743_),
    .B(_0744_),
    .C(_0745_),
    .X(_0746_)
  );
  sky130_fd_sc_hd__xnor2_1 _1239_ (
    .A(_0933_),
    .B(_0643_),
    .Y(_0747_)
  );
  sky130_fd_sc_hd__xnor2_1 _1240_ (
    .A(_0932_),
    .B(_0664_),
    .Y(_0748_)
  );
  sky130_fd_sc_hd__maj3_1 _1241_ (
    .A(_0746_),
    .B(_0747_),
    .C(_0748_),
    .X(_0749_)
  );
  sky130_fd_sc_hd__xor3_1 _1242_ (
    .A(_0746_),
    .B(_0747_),
    .C(_0748_),
    .X(_0750_)
  );
  sky130_fd_sc_hd__xnor2_1 _1243_ (
    .A(_0931_),
    .B(_0686_),
    .Y(_0751_)
  );
  sky130_fd_sc_hd__xnor2_1 _1244_ (
    .A(_0934_),
    .B(_0708_),
    .Y(_0752_)
  );
  sky130_fd_sc_hd__maj3_1 _1245_ (
    .A(_0750_),
    .B(_0751_),
    .C(_0752_),
    .X(_0753_)
  );
  sky130_fd_sc_hd__xnor2_1 _1246_ (
    .A(_0929_),
    .B(_0735_),
    .Y(_0754_)
  );
  sky130_fd_sc_hd__xor3_1 _1247_ (
    .A(_0750_),
    .B(_0751_),
    .C(_0752_),
    .X(_0755_)
  );
  sky130_fd_sc_hd__maj3_1 _1248_ (
    .A(_0743_),
    .B(_0744_),
    .C(_0745_),
    .X(_0756_)
  );
  sky130_fd_sc_hd__a221oi_1 _1249_ (
    .A1(_0749_),
    .A2(_0753_),
    .B1(_0754_),
    .B2(_0755_),
    .C1(_0756_),
    .Y(_0757_)
  );
  sky130_fd_sc_hd__a311oi_1 _1250_ (
    .A1(_0754_),
    .A2(_0755_),
    .A3(_0756_),
    .B1(_0753_),
    .C1(_0749_),
    .Y(_0758_)
  );
  sky130_fd_sc_hd__nor2_1 _1251_ (
    .A(_0757_),
    .B(_0758_),
    .Y(_0836_)
  );
  sky130_fd_sc_hd__xnor2_1 _1252_ (
    .A(_0847_),
    .B(_0568_),
    .Y(_0759_)
  );
  sky130_fd_sc_hd__xnor2_1 _1253_ (
    .A(_0848_),
    .B(_0592_),
    .Y(_0760_)
  );
  sky130_fd_sc_hd__xnor2_1 _1254_ (
    .A(_0850_),
    .B(_0619_),
    .Y(_0761_)
  );
  sky130_fd_sc_hd__xor3_1 _1255_ (
    .A(_0759_),
    .B(_0760_),
    .C(_0761_),
    .X(_0762_)
  );
  sky130_fd_sc_hd__xnor2_1 _1256_ (
    .A(_0853_),
    .B(_0643_),
    .Y(_0763_)
  );
  sky130_fd_sc_hd__xnor2_1 _1257_ (
    .A(_0852_),
    .B(_0664_),
    .Y(_0764_)
  );
  sky130_fd_sc_hd__maj3_1 _1258_ (
    .A(_0762_),
    .B(_0763_),
    .C(_0764_),
    .X(_0765_)
  );
  sky130_fd_sc_hd__xor3_1 _1259_ (
    .A(_0762_),
    .B(_0763_),
    .C(_0764_),
    .X(_0766_)
  );
  sky130_fd_sc_hd__xnor2_1 _1260_ (
    .A(_0851_),
    .B(_0686_),
    .Y(_0767_)
  );
  sky130_fd_sc_hd__xnor2_1 _1261_ (
    .A(_0854_),
    .B(_0708_),
    .Y(_0768_)
  );
  sky130_fd_sc_hd__maj3_1 _1262_ (
    .A(_0766_),
    .B(_0767_),
    .C(_0768_),
    .X(_0769_)
  );
  sky130_fd_sc_hd__xnor2_1 _1263_ (
    .A(_0849_),
    .B(_0735_),
    .Y(_0770_)
  );
  sky130_fd_sc_hd__xor3_1 _1264_ (
    .A(_0766_),
    .B(_0767_),
    .C(_0768_),
    .X(_0771_)
  );
  sky130_fd_sc_hd__maj3_1 _1265_ (
    .A(_0759_),
    .B(_0760_),
    .C(_0761_),
    .X(_0772_)
  );
  sky130_fd_sc_hd__a221oi_1 _1266_ (
    .A1(_0765_),
    .A2(_0769_),
    .B1(_0770_),
    .B2(_0771_),
    .C1(_0772_),
    .Y(_0773_)
  );
  sky130_fd_sc_hd__a311oi_1 _1267_ (
    .A1(_0770_),
    .A2(_0771_),
    .A3(_0772_),
    .B1(_0769_),
    .C1(_0765_),
    .Y(_0774_)
  );
  sky130_fd_sc_hd__nor2_1 _1268_ (
    .A(_0773_),
    .B(_0774_),
    .Y(_0837_)
  );
  sky130_fd_sc_hd__xnor2_1 _1269_ (
    .A(_0855_),
    .B(_0568_),
    .Y(_0775_)
  );
  sky130_fd_sc_hd__xnor2_1 _1270_ (
    .A(_0856_),
    .B(_0592_),
    .Y(_0776_)
  );
  sky130_fd_sc_hd__xnor2_1 _1271_ (
    .A(_0858_),
    .B(_0619_),
    .Y(_0777_)
  );
  sky130_fd_sc_hd__xor3_1 _1272_ (
    .A(_0775_),
    .B(_0776_),
    .C(_0777_),
    .X(_0778_)
  );
  sky130_fd_sc_hd__xnor2_1 _1273_ (
    .A(_0861_),
    .B(_0643_),
    .Y(_0779_)
  );
  sky130_fd_sc_hd__xnor2_1 _1274_ (
    .A(_0860_),
    .B(_0664_),
    .Y(_0780_)
  );
  sky130_fd_sc_hd__maj3_1 _1275_ (
    .A(_0778_),
    .B(_0779_),
    .C(_0780_),
    .X(_0781_)
  );
  sky130_fd_sc_hd__xor3_1 _1276_ (
    .A(_0778_),
    .B(_0779_),
    .C(_0780_),
    .X(_0782_)
  );
  sky130_fd_sc_hd__xnor2_1 _1277_ (
    .A(_0859_),
    .B(_0686_),
    .Y(_0783_)
  );
  sky130_fd_sc_hd__xnor2_1 _1278_ (
    .A(_0862_),
    .B(_0708_),
    .Y(_0784_)
  );
  sky130_fd_sc_hd__maj3_1 _1279_ (
    .A(_0782_),
    .B(_0783_),
    .C(_0784_),
    .X(_0785_)
  );
  sky130_fd_sc_hd__xnor2_1 _1280_ (
    .A(_0857_),
    .B(_0735_),
    .Y(_0786_)
  );
  sky130_fd_sc_hd__xor3_1 _1281_ (
    .A(_0782_),
    .B(_0783_),
    .C(_0784_),
    .X(_0787_)
  );
  sky130_fd_sc_hd__maj3_1 _1282_ (
    .A(_0775_),
    .B(_0776_),
    .C(_0777_),
    .X(_0788_)
  );
  sky130_fd_sc_hd__a221oi_1 _1283_ (
    .A1(_0781_),
    .A2(_0785_),
    .B1(_0786_),
    .B2(_0787_),
    .C1(_0788_),
    .Y(_0789_)
  );
  sky130_fd_sc_hd__a311oi_1 _1284_ (
    .A1(_0786_),
    .A2(_0787_),
    .A3(_0788_),
    .B1(_0785_),
    .C1(_0781_),
    .Y(_0790_)
  );
  sky130_fd_sc_hd__nor2_1 _1285_ (
    .A(_0789_),
    .B(_0790_),
    .Y(_0838_)
  );
  sky130_fd_sc_hd__nand2_1 _1286_ (
    .A(_0830_),
    .B(_0546_),
    .Y(_0791_)
  );
  sky130_fd_sc_hd__and3_1 _1287_ (
    .A(_0545_),
    .B(_0830_),
    .C(_0546_),
    .X(_0792_)
  );
  sky130_fd_sc_hd__nand3_1 _1288_ (
    .A(_0545_),
    .B(_0830_),
    .C(_0546_),
    .Y(_0793_)
  );
  sky130_fd_sc_hd__xnor2_1 _1289_ (
    .A(_0547_),
    .B(_0793_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__nor2_1 _1290_ (
    .A(_0548_),
    .B(_0792_),
    .Y(_0794_)
  );
  sky130_fd_sc_hd__nand2b_1 _1291_ (
    .A_N(_0547_),
    .B(_0548_),
    .Y(_0795_)
  );
  sky130_fd_sc_hd__nand2b_1 _1292_ (
    .A_N(_0548_),
    .B(_0547_),
    .Y(_0796_)
  );
  sky130_fd_sc_hd__a31oi_1 _1293_ (
    .A1(_0792_),
    .A2(_0795_),
    .A3(_0796_),
    .B1(_0794_),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__nand2_1 _1294_ (
    .A(_0547_),
    .B(_0548_),
    .Y(_0797_)
  );
  sky130_fd_sc_hd__nor2_1 _1295_ (
    .A(_0793_),
    .B(_0797_),
    .Y(_0798_)
  );
  sky130_fd_sc_hd__nand2_1 _1296_ (
    .A(_0549_),
    .B(_0798_),
    .Y(_0799_)
  );
  sky130_fd_sc_hd__xor2_1 _1297_ (
    .A(_0549_),
    .B(_0798_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__nand3b_1 _1298_ (
    .A_N(_0550_),
    .B(_0549_),
    .C(_0792_),
    .Y(_0800_)
  );
  sky130_fd_sc_hd__nor2_1 _1299_ (
    .A(_0797_),
    .B(_0800_),
    .Y(_0801_)
  );
  sky130_fd_sc_hd__a21o_1 _1300_ (
    .A1(_0550_),
    .A2(_0799_),
    .B1(_0801_),
    .X(_0443_)
  );
  sky130_fd_sc_hd__nand2_1 _1301_ (
    .A(_0545_),
    .B(_0791_),
    .Y(_0802_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1302_ (
    .A(_0545_),
    .SLEEP(_0791_),
    .X(_0803_)
  );
  sky130_fd_sc_hd__nand2_1 _1303_ (
    .A(_0802_),
    .B(_0803_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__mux2_1 _1304_ (
    .A0(_0831_),
    .A1(_0818_),
    .S(_0803_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__mux2_1 _1305_ (
    .A0(_0832_),
    .A1(_0819_),
    .S(_0803_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__mux2_1 _1306_ (
    .A0(_0833_),
    .A1(_0820_),
    .S(_0803_),
    .X(_0447_)
  );
  sky130_fd_sc_hd__mux2_1 _1307_ (
    .A0(_0834_),
    .A1(_0821_),
    .S(_0803_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__or3_1 _1308_ (
    .A(_0547_),
    .B(_0548_),
    .C(_0793_),
    .X(_0804_)
  );
  sky130_fd_sc_hd__nor3_1 _1309_ (
    .A(_0550_),
    .B(_0549_),
    .C(_0804_),
    .Y(_0805_)
  );
  sky130_fd_sc_hd__mux2_1 _1310_ (
    .A0(_0839_),
    .A1(_0818_),
    .S(_0805_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__mux2_1 _1311_ (
    .A0(_0840_),
    .A1(_0819_),
    .S(_0805_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__mux2_1 _1312_ (
    .A0(_0841_),
    .A1(_0820_),
    .S(_0805_),
    .X(_0451_)
  );
  sky130_fd_sc_hd__mux2_1 _1313_ (
    .A0(_0842_),
    .A1(_0821_),
    .S(_0805_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__mux2_1 _1314_ (
    .A0(_0843_),
    .A1(_0831_),
    .S(_0805_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__mux2_1 _1315_ (
    .A0(_0844_),
    .A1(_0832_),
    .S(_0805_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__mux2_1 _1316_ (
    .A0(_0845_),
    .A1(_0833_),
    .S(_0805_),
    .X(_0455_)
  );
  sky130_fd_sc_hd__mux2_1 _1317_ (
    .A0(_0846_),
    .A1(_0834_),
    .S(_0805_),
    .X(_0456_)
  );
  sky130_fd_sc_hd__or4_1 _1318_ (
    .A(_0550_),
    .B(_0549_),
    .C(_0793_),
    .D(_0795_),
    .X(_0806_)
  );
  sky130_fd_sc_hd__mux2_1 _1319_ (
    .A0(_0818_),
    .A1(_0871_),
    .S(_0806_),
    .X(_0457_)
  );
  sky130_fd_sc_hd__mux2_1 _1320_ (
    .A0(_0819_),
    .A1(_0872_),
    .S(_0806_),
    .X(_0458_)
  );
  sky130_fd_sc_hd__mux2_1 _1321_ (
    .A0(_0820_),
    .A1(_0873_),
    .S(_0806_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__mux2_1 _1322_ (
    .A0(_0821_),
    .A1(_0874_),
    .S(_0806_),
    .X(_0460_)
  );
  sky130_fd_sc_hd__mux2_1 _1323_ (
    .A0(_0831_),
    .A1(_0875_),
    .S(_0806_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__mux2_1 _1324_ (
    .A0(_0832_),
    .A1(_0876_),
    .S(_0806_),
    .X(_0462_)
  );
  sky130_fd_sc_hd__mux2_1 _1325_ (
    .A0(_0833_),
    .A1(_0877_),
    .S(_0806_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__mux2_1 _1326_ (
    .A0(_0834_),
    .A1(_0878_),
    .S(_0806_),
    .X(_0464_)
  );
  sky130_fd_sc_hd__or4_1 _1327_ (
    .A(_0550_),
    .B(_0549_),
    .C(_0793_),
    .D(_0796_),
    .X(_0807_)
  );
  sky130_fd_sc_hd__mux2_1 _1328_ (
    .A0(_0818_),
    .A1(_0863_),
    .S(_0807_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__mux2_1 _1329_ (
    .A0(_0819_),
    .A1(_0864_),
    .S(_0807_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__mux2_1 _1330_ (
    .A0(_0820_),
    .A1(_0865_),
    .S(_0807_),
    .X(_0467_)
  );
  sky130_fd_sc_hd__mux2_1 _1331_ (
    .A0(_0821_),
    .A1(_0866_),
    .S(_0807_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__mux2_1 _1332_ (
    .A0(_0831_),
    .A1(_0867_),
    .S(_0807_),
    .X(_0469_)
  );
  sky130_fd_sc_hd__mux2_1 _1333_ (
    .A0(_0832_),
    .A1(_0868_),
    .S(_0807_),
    .X(_0470_)
  );
  sky130_fd_sc_hd__mux2_1 _1334_ (
    .A0(_0833_),
    .A1(_0869_),
    .S(_0807_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__mux2_1 _1335_ (
    .A0(_0834_),
    .A1(_0870_),
    .S(_0807_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__nor4_1 _1336_ (
    .A(_0550_),
    .B(_0549_),
    .C(_0793_),
    .D(_0797_),
    .Y(_0808_)
  );
  sky130_fd_sc_hd__mux2_1 _1337_ (
    .A0(_0879_),
    .A1(_0818_),
    .S(_0808_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__mux2_1 _1338_ (
    .A0(_0880_),
    .A1(_0819_),
    .S(_0808_),
    .X(_0474_)
  );
  sky130_fd_sc_hd__mux2_1 _1339_ (
    .A0(_0881_),
    .A1(_0820_),
    .S(_0808_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__mux2_1 _1340_ (
    .A0(_0882_),
    .A1(_0821_),
    .S(_0808_),
    .X(_0476_)
  );
  sky130_fd_sc_hd__mux2_1 _1341_ (
    .A0(_0883_),
    .A1(_0831_),
    .S(_0808_),
    .X(_0477_)
  );
  sky130_fd_sc_hd__mux2_1 _1342_ (
    .A0(_0884_),
    .A1(_0832_),
    .S(_0808_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__mux2_1 _1343_ (
    .A0(_0885_),
    .A1(_0833_),
    .S(_0808_),
    .X(_0479_)
  );
  sky130_fd_sc_hd__mux2_1 _1344_ (
    .A0(_0886_),
    .A1(_0834_),
    .S(_0808_),
    .X(_0480_)
  );
  sky130_fd_sc_hd__mux2_1 _1345_ (
    .A0(_0911_),
    .A1(_0818_),
    .S(_0801_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__mux2_1 _1346_ (
    .A0(_0912_),
    .A1(_0819_),
    .S(_0801_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__mux2_1 _1347_ (
    .A0(_0913_),
    .A1(_0820_),
    .S(_0801_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__mux2_1 _1348_ (
    .A0(_0914_),
    .A1(_0821_),
    .S(_0801_),
    .X(_0484_)
  );
  sky130_fd_sc_hd__mux2_1 _1349_ (
    .A0(_0915_),
    .A1(_0831_),
    .S(_0801_),
    .X(_0485_)
  );
  sky130_fd_sc_hd__mux2_1 _1350_ (
    .A0(_0916_),
    .A1(_0832_),
    .S(_0801_),
    .X(_0486_)
  );
  sky130_fd_sc_hd__mux2_1 _1351_ (
    .A0(_0917_),
    .A1(_0833_),
    .S(_0801_),
    .X(_0487_)
  );
  sky130_fd_sc_hd__mux2_1 _1352_ (
    .A0(_0918_),
    .A1(_0834_),
    .S(_0801_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__nor3b_1 _1353_ (
    .A(_0804_),
    .B(_0550_),
    .C_N(_0549_),
    .Y(_0809_)
  );
  sky130_fd_sc_hd__mux2_1 _1354_ (
    .A0(_0887_),
    .A1(_0818_),
    .S(_0809_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__mux2_1 _1355_ (
    .A0(_0888_),
    .A1(_0819_),
    .S(_0809_),
    .X(_0490_)
  );
  sky130_fd_sc_hd__mux2_1 _1356_ (
    .A0(_0889_),
    .A1(_0820_),
    .S(_0809_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__mux2_1 _1357_ (
    .A0(_0890_),
    .A1(_0821_),
    .S(_0809_),
    .X(_0492_)
  );
  sky130_fd_sc_hd__mux2_1 _1358_ (
    .A0(_0891_),
    .A1(_0831_),
    .S(_0809_),
    .X(_0493_)
  );
  sky130_fd_sc_hd__mux2_1 _1359_ (
    .A0(_0892_),
    .A1(_0832_),
    .S(_0809_),
    .X(_0494_)
  );
  sky130_fd_sc_hd__mux2_1 _1360_ (
    .A0(_0893_),
    .A1(_0833_),
    .S(_0809_),
    .X(_0495_)
  );
  sky130_fd_sc_hd__mux2_1 _1361_ (
    .A0(_0894_),
    .A1(_0834_),
    .S(_0809_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__nand2b_1 _1362_ (
    .A_N(_0549_),
    .B(_0550_),
    .Y(_0810_)
  );
  sky130_fd_sc_hd__nor2_1 _1363_ (
    .A(_0804_),
    .B(_0810_),
    .Y(_0811_)
  );
  sky130_fd_sc_hd__mux2_1 _1364_ (
    .A0(_0919_),
    .A1(_0818_),
    .S(_0811_),
    .X(_0497_)
  );
  sky130_fd_sc_hd__mux2_1 _1365_ (
    .A0(_0920_),
    .A1(_0819_),
    .S(_0811_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__mux2_1 _1366_ (
    .A0(_0921_),
    .A1(_0820_),
    .S(_0811_),
    .X(_0499_)
  );
  sky130_fd_sc_hd__mux2_1 _1367_ (
    .A0(_0922_),
    .A1(_0821_),
    .S(_0811_),
    .X(_0500_)
  );
  sky130_fd_sc_hd__mux2_1 _1368_ (
    .A0(_0923_),
    .A1(_0831_),
    .S(_0811_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__mux2_1 _1369_ (
    .A0(_0924_),
    .A1(_0832_),
    .S(_0811_),
    .X(_0502_)
  );
  sky130_fd_sc_hd__mux2_1 _1370_ (
    .A0(_0925_),
    .A1(_0833_),
    .S(_0811_),
    .X(_0503_)
  );
  sky130_fd_sc_hd__mux2_1 _1371_ (
    .A0(_0926_),
    .A1(_0834_),
    .S(_0811_),
    .X(_0504_)
  );
  sky130_fd_sc_hd__nor2_1 _1372_ (
    .A(_0796_),
    .B(_0800_),
    .Y(_0812_)
  );
  sky130_fd_sc_hd__mux2_1 _1373_ (
    .A0(_0895_),
    .A1(_0818_),
    .S(_0812_),
    .X(_0505_)
  );
  sky130_fd_sc_hd__mux2_1 _1374_ (
    .A0(_0896_),
    .A1(_0819_),
    .S(_0812_),
    .X(_0506_)
  );
  sky130_fd_sc_hd__mux2_1 _1375_ (
    .A0(_0897_),
    .A1(_0820_),
    .S(_0812_),
    .X(_0507_)
  );
  sky130_fd_sc_hd__mux2_1 _1376_ (
    .A0(_0898_),
    .A1(_0821_),
    .S(_0812_),
    .X(_0508_)
  );
  sky130_fd_sc_hd__mux2_1 _1377_ (
    .A0(_0899_),
    .A1(_0831_),
    .S(_0812_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__mux2_1 _1378_ (
    .A0(_0900_),
    .A1(_0832_),
    .S(_0812_),
    .X(_0510_)
  );
  sky130_fd_sc_hd__mux2_1 _1379_ (
    .A0(_0901_),
    .A1(_0833_),
    .S(_0812_),
    .X(_0511_)
  );
  sky130_fd_sc_hd__mux2_1 _1380_ (
    .A0(_0902_),
    .A1(_0834_),
    .S(_0812_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _1381_ (
    .A(_0793_),
    .SLEEP(_0810_),
    .X(_0813_)
  );
  sky130_fd_sc_hd__nor2_1 _1382_ (
    .A(_0796_),
    .B(_0813_),
    .Y(_0814_)
  );
  sky130_fd_sc_hd__mux2_1 _1383_ (
    .A0(_0927_),
    .A1(_0818_),
    .S(_0814_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__mux2_1 _1384_ (
    .A0(_0928_),
    .A1(_0819_),
    .S(_0814_),
    .X(_0514_)
  );
  sky130_fd_sc_hd__mux2_1 _1385_ (
    .A0(_0929_),
    .A1(_0820_),
    .S(_0814_),
    .X(_0515_)
  );
  sky130_fd_sc_hd__mux2_1 _1386_ (
    .A0(_0930_),
    .A1(_0821_),
    .S(_0814_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__mux2_1 _1387_ (
    .A0(_0931_),
    .A1(_0831_),
    .S(_0814_),
    .X(_0517_)
  );
  sky130_fd_sc_hd__mux2_1 _1388_ (
    .A0(_0932_),
    .A1(_0832_),
    .S(_0814_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__mux2_1 _1389_ (
    .A0(_0933_),
    .A1(_0833_),
    .S(_0814_),
    .X(_0519_)
  );
  sky130_fd_sc_hd__mux2_1 _1390_ (
    .A0(_0934_),
    .A1(_0834_),
    .S(_0814_),
    .X(_0520_)
  );
  sky130_fd_sc_hd__nor2_1 _1391_ (
    .A(_0795_),
    .B(_0800_),
    .Y(_0815_)
  );
  sky130_fd_sc_hd__mux2_1 _1392_ (
    .A0(_0903_),
    .A1(_0818_),
    .S(_0815_),
    .X(_0521_)
  );
  sky130_fd_sc_hd__mux2_1 _1393_ (
    .A0(_0904_),
    .A1(_0819_),
    .S(_0815_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__mux2_1 _1394_ (
    .A0(_0905_),
    .A1(_0820_),
    .S(_0815_),
    .X(_0523_)
  );
  sky130_fd_sc_hd__mux2_1 _1395_ (
    .A0(_0906_),
    .A1(_0821_),
    .S(_0815_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__mux2_1 _1396_ (
    .A0(_0907_),
    .A1(_0831_),
    .S(_0815_),
    .X(_0525_)
  );
  sky130_fd_sc_hd__mux2_1 _1397_ (
    .A0(_0908_),
    .A1(_0832_),
    .S(_0815_),
    .X(_0526_)
  );
  sky130_fd_sc_hd__mux2_1 _1398_ (
    .A0(_0909_),
    .A1(_0833_),
    .S(_0815_),
    .X(_0527_)
  );
  sky130_fd_sc_hd__mux2_1 _1399_ (
    .A0(_0910_),
    .A1(_0834_),
    .S(_0815_),
    .X(_0528_)
  );
  sky130_fd_sc_hd__nor2_1 _1400_ (
    .A(_0795_),
    .B(_0813_),
    .Y(_0816_)
  );
  sky130_fd_sc_hd__mux2_1 _1401_ (
    .A0(_0847_),
    .A1(_0818_),
    .S(_0816_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__mux2_1 _1402_ (
    .A0(_0848_),
    .A1(_0819_),
    .S(_0816_),
    .X(_0530_)
  );
  sky130_fd_sc_hd__mux2_1 _1403_ (
    .A0(_0849_),
    .A1(_0820_),
    .S(_0816_),
    .X(_0531_)
  );
  sky130_fd_sc_hd__mux2_1 _1404_ (
    .A0(_0850_),
    .A1(_0821_),
    .S(_0816_),
    .X(_0532_)
  );
  sky130_fd_sc_hd__mux2_1 _1405_ (
    .A0(_0851_),
    .A1(_0831_),
    .S(_0816_),
    .X(_0533_)
  );
  sky130_fd_sc_hd__mux2_1 _1406_ (
    .A0(_0852_),
    .A1(_0832_),
    .S(_0816_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__mux2_1 _1407_ (
    .A0(_0853_),
    .A1(_0833_),
    .S(_0816_),
    .X(_0535_)
  );
  sky130_fd_sc_hd__mux2_1 _1408_ (
    .A0(_0854_),
    .A1(_0834_),
    .S(_0816_),
    .X(_0536_)
  );
  sky130_fd_sc_hd__nor2_1 _1409_ (
    .A(_0797_),
    .B(_0813_),
    .Y(_0817_)
  );
  sky130_fd_sc_hd__mux2_1 _1410_ (
    .A0(_0855_),
    .A1(_0818_),
    .S(_0817_),
    .X(_0537_)
  );
  sky130_fd_sc_hd__mux2_1 _1411_ (
    .A0(_0856_),
    .A1(_0819_),
    .S(_0817_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__mux2_1 _1412_ (
    .A0(_0857_),
    .A1(_0820_),
    .S(_0817_),
    .X(_0539_)
  );
  sky130_fd_sc_hd__mux2_1 _1413_ (
    .A0(_0858_),
    .A1(_0821_),
    .S(_0817_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__mux2_1 _1414_ (
    .A0(_0859_),
    .A1(_0831_),
    .S(_0817_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__mux2_1 _1415_ (
    .A0(_0860_),
    .A1(_0832_),
    .S(_0817_),
    .X(_0542_)
  );
  sky130_fd_sc_hd__mux2_1 _1416_ (
    .A0(_0861_),
    .A1(_0833_),
    .S(_0817_),
    .X(_0543_)
  );
  sky130_fd_sc_hd__mux2_1 _1417_ (
    .A0(_0862_),
    .A1(_0834_),
    .S(_0817_),
    .X(_0544_)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1418_ (
    .CLK(clk),
    .D(_0937_),
    .Q(load_state[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1419_ (
    .CLK(clk),
    .D(_0938_),
    .Q(load_state[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1420_ (
    .CLK(clk),
    .D(_0939_),
    .Q(load_state[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1421_ (
    .CLK(clk),
    .D(_0940_),
    .Q(load_state[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1422_ (
    .CLK(clk),
    .D(_0941_),
    .Q(bit_index),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1423_ (
    .CLK(clk),
    .D(_0942_),
    .Q(temp_weight[0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1424_ (
    .CLK(clk),
    .D(_0943_),
    .Q(temp_weight[1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1425_ (
    .CLK(clk),
    .D(_0944_),
    .Q(temp_weight[2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1426_ (
    .CLK(clk),
    .D(_0945_),
    .Q(temp_weight[3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1427_ (
    .CLK(clk),
    .D(_0946_),
    .Q(\weights[0] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1428_ (
    .CLK(clk),
    .D(_0947_),
    .Q(\weights[0] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1429_ (
    .CLK(clk),
    .D(_0948_),
    .Q(\weights[0] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1430_ (
    .CLK(clk),
    .D(_0949_),
    .Q(\weights[0] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1431_ (
    .CLK(clk),
    .D(_0950_),
    .Q(\weights[0] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1432_ (
    .CLK(clk),
    .D(_0951_),
    .Q(\weights[0] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1433_ (
    .CLK(clk),
    .D(_0952_),
    .Q(\weights[0] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1434_ (
    .CLK(clk),
    .D(_0953_),
    .Q(\weights[0] [7]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1435_ (
    .CLK(clk),
    .D(_0954_),
    .Q(\weights[2] [0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1436_ (
    .CLK(clk),
    .D(_0955_),
    .Q(\weights[2] [1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1437_ (
    .CLK(clk),
    .D(_0956_),
    .Q(\weights[2] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1438_ (
    .CLK(clk),
    .D(_0957_),
    .Q(\weights[2] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1439_ (
    .CLK(clk),
    .D(_0958_),
    .Q(\weights[2] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1440_ (
    .CLK(clk),
    .D(_0959_),
    .Q(\weights[2] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1441_ (
    .CLK(clk),
    .D(_0960_),
    .Q(\weights[2] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1442_ (
    .CLK(clk),
    .D(_0961_),
    .Q(\weights[2] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1443_ (
    .CLK(clk),
    .D(_0962_),
    .Q(\weights[1] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1444_ (
    .CLK(clk),
    .D(_0963_),
    .Q(\weights[1] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1445_ (
    .CLK(clk),
    .D(_0964_),
    .Q(\weights[1] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1446_ (
    .CLK(clk),
    .D(_0965_),
    .Q(\weights[1] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1447_ (
    .CLK(clk),
    .D(_0966_),
    .Q(\weights[1] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1448_ (
    .CLK(clk),
    .D(_0967_),
    .Q(\weights[1] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1449_ (
    .CLK(clk),
    .D(_0968_),
    .Q(\weights[1] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1450_ (
    .CLK(clk),
    .D(_0969_),
    .Q(\weights[1] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1451_ (
    .CLK(clk),
    .D(_0970_),
    .Q(\weights[3] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1452_ (
    .CLK(clk),
    .D(_0971_),
    .Q(\weights[3] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1453_ (
    .CLK(clk),
    .D(_0972_),
    .Q(\weights[3] [2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1454_ (
    .CLK(clk),
    .D(_0973_),
    .Q(\weights[3] [3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1455_ (
    .CLK(clk),
    .D(_0974_),
    .Q(\weights[3] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1456_ (
    .CLK(clk),
    .D(_0975_),
    .Q(\weights[3] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1457_ (
    .CLK(clk),
    .D(_0976_),
    .Q(\weights[3] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1458_ (
    .CLK(clk),
    .D(_0977_),
    .Q(\weights[3] [7]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1459_ (
    .CLK(clk),
    .D(_0978_),
    .Q(\weights[7] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1460_ (
    .CLK(clk),
    .D(_0979_),
    .Q(\weights[7] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1461_ (
    .CLK(clk),
    .D(_0980_),
    .Q(\weights[7] [2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1462_ (
    .CLK(clk),
    .D(_0981_),
    .Q(\weights[7] [3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1463_ (
    .CLK(clk),
    .D(_0982_),
    .Q(\weights[7] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1464_ (
    .CLK(clk),
    .D(_0983_),
    .Q(\weights[7] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1465_ (
    .CLK(clk),
    .D(_0984_),
    .Q(\weights[7] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1466_ (
    .CLK(clk),
    .D(_0985_),
    .Q(\weights[7] [7]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1467_ (
    .CLK(clk),
    .D(_0986_),
    .Q(\weights[4] [0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1468_ (
    .CLK(clk),
    .D(_0987_),
    .Q(\weights[4] [1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1469_ (
    .CLK(clk),
    .D(_0988_),
    .Q(\weights[4] [2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1470_ (
    .CLK(clk),
    .D(_0989_),
    .Q(\weights[4] [3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1471_ (
    .CLK(clk),
    .D(_0990_),
    .Q(\weights[4] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1472_ (
    .CLK(clk),
    .D(_0991_),
    .Q(\weights[4] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1473_ (
    .CLK(clk),
    .D(_0992_),
    .Q(\weights[4] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1474_ (
    .CLK(clk),
    .D(_0993_),
    .Q(\weights[4] [7]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1475_ (
    .CLK(clk),
    .D(_0994_),
    .Q(\weights[8] [0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1476_ (
    .CLK(clk),
    .D(_0995_),
    .Q(\weights[8] [1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1477_ (
    .CLK(clk),
    .D(_0996_),
    .Q(\weights[8] [2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1478_ (
    .CLK(clk),
    .D(_0997_),
    .Q(\weights[8] [3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1479_ (
    .CLK(clk),
    .D(_0998_),
    .Q(\weights[8] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1480_ (
    .CLK(clk),
    .D(_0999_),
    .Q(\weights[8] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1481_ (
    .CLK(clk),
    .D(_1000_),
    .Q(\weights[8] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1482_ (
    .CLK(clk),
    .D(_1001_),
    .Q(\weights[8] [7]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1483_ (
    .CLK(clk),
    .D(_1002_),
    .Q(\weights[5] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1484_ (
    .CLK(clk),
    .D(_1003_),
    .Q(\weights[5] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1485_ (
    .CLK(clk),
    .D(_1004_),
    .Q(\weights[5] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1486_ (
    .CLK(clk),
    .D(_1005_),
    .Q(\weights[5] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1487_ (
    .CLK(clk),
    .D(_1006_),
    .Q(\weights[5] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1488_ (
    .CLK(clk),
    .D(_1007_),
    .Q(\weights[5] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1489_ (
    .CLK(clk),
    .D(_1008_),
    .Q(\weights[5] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1490_ (
    .CLK(clk),
    .D(_1009_),
    .Q(\weights[5] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1491_ (
    .CLK(clk),
    .D(_1010_),
    .Q(\weights[9] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1492_ (
    .CLK(clk),
    .D(_1011_),
    .Q(\weights[9] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1493_ (
    .CLK(clk),
    .D(_1012_),
    .Q(\weights[9] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1494_ (
    .CLK(clk),
    .D(_1013_),
    .Q(\weights[9] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1495_ (
    .CLK(clk),
    .D(_1014_),
    .Q(\weights[9] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1496_ (
    .CLK(clk),
    .D(_1015_),
    .Q(\weights[9] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1497_ (
    .CLK(clk),
    .D(_1016_),
    .Q(\weights[9] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1498_ (
    .CLK(clk),
    .D(_1017_),
    .Q(\weights[9] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1499_ (
    .CLK(clk),
    .D(_1018_),
    .Q(\weights[6] [0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1500_ (
    .CLK(clk),
    .D(_1019_),
    .Q(\weights[6] [1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1501_ (
    .CLK(clk),
    .D(_1020_),
    .Q(\weights[6] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1502_ (
    .CLK(clk),
    .D(_1021_),
    .Q(\weights[6] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1503_ (
    .CLK(clk),
    .D(_1022_),
    .Q(\weights[6] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1504_ (
    .CLK(clk),
    .D(_1023_),
    .Q(\weights[6] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1505_ (
    .CLK(clk),
    .D(_1024_),
    .Q(\weights[6] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1506_ (
    .CLK(clk),
    .D(_1025_),
    .Q(\weights[6] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1507_ (
    .CLK(clk),
    .D(_1026_),
    .Q(\weights[10] [0]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1508_ (
    .CLK(clk),
    .D(_1027_),
    .Q(\weights[10] [1]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1509_ (
    .CLK(clk),
    .D(_1028_),
    .Q(\weights[10] [2]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1510_ (
    .CLK(clk),
    .D(_1029_),
    .Q(\weights[10] [3]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1511_ (
    .CLK(clk),
    .D(_1030_),
    .Q(\weights[10] [4]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1512_ (
    .CLK(clk),
    .D(_1031_),
    .Q(\weights[10] [5]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1513_ (
    .CLK(clk),
    .D(_1032_),
    .Q(\weights[10] [6]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1514_ (
    .CLK(clk),
    .D(_1033_),
    .Q(\weights[10] [7]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1515_ (
    .CLK(clk),
    .D(_1034_),
    .Q(\weights[11] [0]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1516_ (
    .CLK(clk),
    .D(_1035_),
    .Q(\weights[11] [1]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1517_ (
    .CLK(clk),
    .D(_1036_),
    .Q(\weights[11] [2]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1518_ (
    .CLK(clk),
    .D(_1037_),
    .Q(\weights[11] [3]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1519_ (
    .CLK(clk),
    .D(_1038_),
    .Q(\weights[11] [4]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfrtp_1 _1520_ (
    .CLK(clk),
    .D(_1039_),
    .Q(\weights[11] [5]),
    .RESET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1521_ (
    .CLK(clk),
    .D(_1040_),
    .Q(\weights[11] [6]),
    .SET_B(rst_n)
  );
  (* src = "src/project.v:40.1-69.4" *)
  sky130_fd_sc_hd__dfstp_2 _1522_ (
    .CLK(clk),
    .D(_1041_),
    .Q(\weights[11] [7]),
    .SET_B(rst_n)
  );
  assign _0935_[4:1] = load_state[4:1];
  assign _0936_[0] = _0935_[0];
  assign neuron_out3 = uo_out[7:4];
  assign uio_oe = 8'h00;
  assign uio_out = 8'h00;
  assign uo_out[3:0] = \weights[0] [7:4];
  assign _0839_ = \weights[0] [0];
  assign _0822_ = ui_in[0];
  assign _0840_ = \weights[0] [1];
  assign _0823_ = ui_in[1];
  assign _0842_ = \weights[0] [3];
  assign _0825_ = ui_in[3];
  assign _0845_ = \weights[0] [6];
  assign _0828_ = ui_in[6];
  assign _0844_ = \weights[0] [5];
  assign _0827_ = ui_in[5];
  assign _0843_ = \weights[0] [4];
  assign _0826_ = ui_in[4];
  assign _0846_ = \weights[0] [7];
  assign _0829_ = ui_in[7];
  assign _0841_ = \weights[0] [2];
  assign _0824_ = ui_in[2];
  assign _0919_ = \weights[8] [0];
  assign _0863_ = \weights[1] [0];
  assign _0864_ = \weights[1] [1];
  assign _0866_ = \weights[1] [3];
  assign _0869_ = \weights[1] [6];
  assign _0868_ = \weights[1] [5];
  assign _0867_ = \weights[1] [4];
  assign _0870_ = \weights[1] [7];
  assign _0865_ = \weights[1] [2];
  assign _0920_ = \weights[8] [1];
  assign _0879_ = \weights[3] [0];
  assign _0880_ = \weights[3] [1];
  assign _0882_ = \weights[3] [3];
  assign _0885_ = \weights[3] [6];
  assign _0884_ = \weights[3] [5];
  assign _0883_ = \weights[3] [4];
  assign _0886_ = \weights[3] [7];
  assign _0881_ = \weights[3] [2];
  assign _0922_ = \weights[8] [3];
  assign _0903_ = \weights[6] [0];
  assign _0904_ = \weights[6] [1];
  assign _0906_ = \weights[6] [3];
  assign _0909_ = \weights[6] [6];
  assign _0908_ = \weights[6] [5];
  assign _0907_ = \weights[6] [4];
  assign _0910_ = \weights[6] [7];
  assign _0905_ = \weights[6] [2];
  assign _0925_ = \weights[8] [6];
  assign _0895_ = \weights[5] [0];
  assign _0896_ = \weights[5] [1];
  assign _0898_ = \weights[5] [3];
  assign _0901_ = \weights[5] [6];
  assign _0900_ = \weights[5] [5];
  assign _0899_ = \weights[5] [4];
  assign _0902_ = \weights[5] [7];
  assign _0897_ = \weights[5] [2];
  assign _0924_ = \weights[8] [5];
  assign _0887_ = \weights[4] [0];
  assign _0888_ = \weights[4] [1];
  assign _0890_ = \weights[4] [3];
  assign _0893_ = \weights[4] [6];
  assign _0892_ = \weights[4] [5];
  assign _0891_ = \weights[4] [4];
  assign _0894_ = \weights[4] [7];
  assign _0889_ = \weights[4] [2];
  assign _0923_ = \weights[8] [4];
  assign _0911_ = \weights[7] [0];
  assign _0912_ = \weights[7] [1];
  assign _0914_ = \weights[7] [3];
  assign _0917_ = \weights[7] [6];
  assign _0916_ = \weights[7] [5];
  assign _0915_ = \weights[7] [4];
  assign _0918_ = \weights[7] [7];
  assign _0913_ = \weights[7] [2];
  assign _0926_ = \weights[8] [7];
  assign _0871_ = \weights[2] [0];
  assign _0872_ = \weights[2] [1];
  assign _0874_ = \weights[2] [3];
  assign _0877_ = \weights[2] [6];
  assign _0876_ = \weights[2] [5];
  assign _0875_ = \weights[2] [4];
  assign _0878_ = \weights[2] [7];
  assign _0873_ = \weights[2] [2];
  assign _0921_ = \weights[8] [2];
  assign uo_out[4] = _0835_;
  assign _0927_ = \weights[9] [0];
  assign _0928_ = \weights[9] [1];
  assign _0930_ = \weights[9] [3];
  assign _0933_ = \weights[9] [6];
  assign _0932_ = \weights[9] [5];
  assign _0931_ = \weights[9] [4];
  assign _0934_ = \weights[9] [7];
  assign _0929_ = \weights[9] [2];
  assign uo_out[5] = _0836_;
  assign _0847_ = \weights[10] [0];
  assign _0848_ = \weights[10] [1];
  assign _0850_ = \weights[10] [3];
  assign _0853_ = \weights[10] [6];
  assign _0852_ = \weights[10] [5];
  assign _0851_ = \weights[10] [4];
  assign _0854_ = \weights[10] [7];
  assign _0849_ = \weights[10] [2];
  assign uo_out[6] = _0837_;
  assign _0855_ = \weights[11] [0];
  assign _0856_ = \weights[11] [1];
  assign _0858_ = \weights[11] [3];
  assign _0861_ = \weights[11] [6];
  assign _0860_ = \weights[11] [5];
  assign _0859_ = \weights[11] [4];
  assign _0862_ = \weights[11] [7];
  assign _0857_ = \weights[11] [2];
  assign uo_out[7] = _0838_;
  assign _0547_ = load_state[0];
  assign _0545_ = bit_index;
  assign _0830_ = uio_in[3];
  assign _0546_ = ena;
  assign _0548_ = load_state[1];
  assign _0550_ = load_state[3];
  assign _0549_ = load_state[2];
  assign _0937_ = _0440_;
  assign _0938_ = _0441_;
  assign _0939_ = _0442_;
  assign _0940_ = _0443_;
  assign _0941_ = _0444_;
  assign _0818_ = temp_weight[0];
  assign _0831_ = uio_in[4];
  assign _0942_ = _0445_;
  assign _0819_ = temp_weight[1];
  assign _0832_ = uio_in[5];
  assign _0943_ = _0446_;
  assign _0820_ = temp_weight[2];
  assign _0833_ = uio_in[6];
  assign _0944_ = _0447_;
  assign _0821_ = temp_weight[3];
  assign _0834_ = uio_in[7];
  assign _0945_ = _0448_;
  assign _0946_ = _0449_;
  assign _0947_ = _0450_;
  assign _0948_ = _0451_;
  assign _0949_ = _0452_;
  assign _0950_ = _0453_;
  assign _0951_ = _0454_;
  assign _0952_ = _0455_;
  assign _0953_ = _0456_;
  assign _0954_ = _0457_;
  assign _0955_ = _0458_;
  assign _0956_ = _0459_;
  assign _0957_ = _0460_;
  assign _0958_ = _0461_;
  assign _0959_ = _0462_;
  assign _0960_ = _0463_;
  assign _0961_ = _0464_;
  assign _0962_ = _0465_;
  assign _0963_ = _0466_;
  assign _0964_ = _0467_;
  assign _0965_ = _0468_;
  assign _0966_ = _0469_;
  assign _0967_ = _0470_;
  assign _0968_ = _0471_;
  assign _0969_ = _0472_;
  assign _0970_ = _0473_;
  assign _0971_ = _0474_;
  assign _0972_ = _0475_;
  assign _0973_ = _0476_;
  assign _0974_ = _0477_;
  assign _0975_ = _0478_;
  assign _0976_ = _0479_;
  assign _0977_ = _0480_;
  assign _0978_ = _0481_;
  assign _0979_ = _0482_;
  assign _0980_ = _0483_;
  assign _0981_ = _0484_;
  assign _0982_ = _0485_;
  assign _0983_ = _0486_;
  assign _0984_ = _0487_;
  assign _0985_ = _0488_;
  assign _0986_ = _0489_;
  assign _0987_ = _0490_;
  assign _0988_ = _0491_;
  assign _0989_ = _0492_;
  assign _0990_ = _0493_;
  assign _0991_ = _0494_;
  assign _0992_ = _0495_;
  assign _0993_ = _0496_;
  assign _0994_ = _0497_;
  assign _0995_ = _0498_;
  assign _0996_ = _0499_;
  assign _0997_ = _0500_;
  assign _0998_ = _0501_;
  assign _0999_ = _0502_;
  assign _1000_ = _0503_;
  assign _1001_ = _0504_;
  assign _1002_ = _0505_;
  assign _1003_ = _0506_;
  assign _1004_ = _0507_;
  assign _1005_ = _0508_;
  assign _1006_ = _0509_;
  assign _1007_ = _0510_;
  assign _1008_ = _0511_;
  assign _1009_ = _0512_;
  assign _1010_ = _0513_;
  assign _1011_ = _0514_;
  assign _1012_ = _0515_;
  assign _1013_ = _0516_;
  assign _1014_ = _0517_;
  assign _1015_ = _0518_;
  assign _1016_ = _0519_;
  assign _1017_ = _0520_;
  assign _1018_ = _0521_;
  assign _1019_ = _0522_;
  assign _1020_ = _0523_;
  assign _1021_ = _0524_;
  assign _1022_ = _0525_;
  assign _1023_ = _0526_;
  assign _1024_ = _0527_;
  assign _1025_ = _0528_;
  assign _1026_ = _0529_;
  assign _1027_ = _0530_;
  assign _1028_ = _0531_;
  assign _1029_ = _0532_;
  assign _1030_ = _0533_;
  assign _1031_ = _0534_;
  assign _1032_ = _0535_;
  assign _1033_ = _0536_;
  assign _1034_ = _0537_;
  assign _1035_ = _0538_;
  assign _1036_ = _0539_;
  assign _1037_ = _0540_;
  assign _1038_ = _0541_;
  assign _1039_ = _0542_;
  assign _1040_ = _0543_;
  assign _1041_ = _0544_;
endmodule
