name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25a
        with:
          pdk: sky130
          tools-ref: ttsky25a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25a
        with:
          pdk: sky130

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clean old GitHub Pages artifact
        run: |
          echo "Removing previous github-pages artifacts if they exist"
          rm -f ./sim_build/viewer/github-pages.zip || true

      - uses: TinyTapeout/tt-gds-action/viewer@ttsky25a
        with:
          pdk: sky130
