name: reharden

on:
  push:
  workflow_dispatch:
    inputs:
      openlane_tag:
        description: 'Openlane tag'
        required: false
        default: '2.2.9'

jobs:
  reharden:
    strategy:
      fail-fast: false
      matrix:
        project:
          #- tt_um_chip_rom # skip: chip ROM
          - tt_um_10_vga_crossyroad
          #- tt_um_13hihi31_tdc # skip: analog
          - tt_um_2048_vga_game
          - tt_um_32_bit_fp_ALU_S_M
          #- tt_um_3v_inverter_SiliconeGuide # skip: analog
          - tt_um_6502
          - tt_um_7FM_ShadyPong
          - tt_um_8bitalu
          - tt_um_Alida_DutyCycleMeter
          - tt_um_AriaMitraClock
          - tt_um_AriaMitraGames
          - tt_um_BMSCE_T2
          - tt_um_BNN
          - tt_um_BryanKuang_mac_peripheral
          #- tt_um_DAC1 # skip: analog
          #- tt_um_DalinEM_asic_1 # skip: analog
          - tt_um_DelosReyesJordan_HDL
          #- tt_um_Enhanced_pll # skip: analog
          - tt_um_FFT_engine
          - tt_um_IZ_RG_22
          - tt_um_LIF_neuron
          #- tt_um_LPCAS_TP1 # skip: analog
          #- tt_um_Maj_opamp # skip: analog
          - tt_um_MichaelBell_hs_mul
          - tt_um_MichaelBell_mandelbrot
          - tt_um_MichaelBell_rle_vga
          #- tt_um_NE567Mixer28 # skip: analog
          - tt_um_Richard28277
          - tt_um_RoyTr16
          - tt_um_SNPU
          - tt_um_Scimia_oscillator_tester
          - tt_um_SummerTT_HDL
          - tt_um_TT06_pwm
          - tt_um_TT16
          - tt_um_TensorFlowE
          - tt_um_Xgamer1999_LIF
          #- tt_um_acidonitroso_programmable_threshold_voltage_sensor # skip: analog
          #- tt_um_adc_dac_tern_alu # skip: analog
          - tt_um_adpll
          - tt_um_ag_priority_encoder_parity_checker
          #- tt_um_alexandercoabad_mixedsignal # skip: analog
          #- tt_um_algofoogle_vga_matrix_dac # skip: analog
          - tt_um_alu_4bit_wrapper
          #- tt_um_analog_example # skip: analog
          #- tt_um_analog_factory_test # skip: analog
          - tt_um_andyshor_demux
          #- tt_um_anweiteck_2stageCMOSOpAmp # skip: analog
          #- tt_um_assaify_mssf_pll # skip: analog
          - tt_um_axi4lite_top
          - tt_um_betz_morse_keyer
          - tt_um_bit_serial_cpu_top
          - tt_um_bitty
          - tt_um_bleeptrack_cc1
          - tt_um_bleeptrack_cc2
          - tt_um_bleeptrack_cc3
          - tt_um_bleeptrack_cc4
          - tt_um_brandonramos_VGA_Pong_with_NES_Controllers
          #- tt_um_brandonramos_opamp_ladder # skip: analog
          - tt_um_braun_mult
          - tt_um_brent_kung
          - tt_um_cache_controller
          - tt_um_chrishtet_LIF
          - tt_um_combo_haz
          - tt_um_customalu
          #- tt_um_cw_vref # skip: analog
          - tt_um_dac12
          #- tt_um_dac_test3v3 # skip: analog
          - tt_um_dco
          - tt_um_delaychain
          #- tt_um_diff # skip: analog
          - tt_um_digital_playground
          - tt_um_dlmiles_tqvph_i2c
          - tt_um_dma
          - tt_um_dpmunit
          - tt_um_dteal_awg
          - tt_um_ece298a_8_bit_cpu_top
          - tt_um_edwintorok
          #- tt_um_emmersonv_tiq_adc # skip: analog
          - tt_um_ev_motor_control
          - tt_um_factory_test
          - tt_um_fifo
          - tt_um_flash_raid_controller
          - tt_um_flummer_ltc
          - tt_um_frequency_counter
          - tt_um_fsm_haz
          - tt_um_galaguna_PostSys
          - tt_um_gamepad_pmod_demo
          - tt_um_gray_sobel
          - tt_um_hack_cpu
          - tt_um_htfab_split_flops
          - tt_um_jamesrosssharp_1bitam
          - tt_um_jamesrosssharp_tiny1bitam
          - tt_um_javibajocero_top
          #- tt_um_jnw_wulffern # skip: analog
          - tt_um_jonathan_thing_vga
          - tt_um_jonnor_pdm_microphone
          #- tt_um_jyblue1001_pll # skip: analog
          - tt_um_kb2ghz_xalu
          - tt_um_kianV_rv32ima_uLinux_SoC
          - tt_um_kishorenetheti_tt16_mips
          - tt_um_krisjdev_manchester_baby
          - tt_um_lcd_controller_Andres078
          - tt_um_led_matrix_driver
          - tt_um_lfsr_stevej
          - tt_um_librelane3_test
          - tt_um_limpix31_r0
          - tt_um_log_afpm
          - tt_um_mac
          - tt_um_mac_spst_tiny
          - tt_um_markgarnold_pdp8
          - tt_um_marxkar_jtag
          - tt_um_matrag_chirp_top
          #- tt_um_mattvenn_analog_ring_osc # skip: analog
          #- tt_um_mattvenn_r2r_dac_3v3 # skip: analog
          - tt_um_mattvenn_spi_test
          #- tt_um_mbikovitsky_audio_player # skip: analog
          - tt_um_mbist
          - tt_um_mcs4_cpu
          - tt_um_micro_tiles_container
          - tt_um_micro_tiles_container_group2
          - tt_um_mikael
          - tt_um_minirisc
          - tt_um_mod6_counter
          #- tt_um_mosbius # skip: analog
          - tt_um_murmann_group
          - tt_um_myprocessor
          - tt_um_nitelich_conway
          - tt_um_nitelich_riscyjr
          - tt_um_nvious_graphics
          - tt_um_openfpga22
          - tt_um_openram_top
          #- tt_um_oscillating_bones # skip: analog
          - tt_um_pchri03_levenshtein
          - tt_um_pe_simonbju
          - tt_um_plc_prg
          - tt_um_program_counter_top_level
          - tt_um_pwen
          - tt_um_quarren42_demoscene_top
          #- tt_um_r2r_dac # skip: analog
          #- tt_um_rburt16_bias_generator # skip: analog
          #- tt_um_rburt16_opamp_3stage # skip: analog
          - tt_um_rebeccargb_colorbars
          - tt_um_rebeccargb_dipped
          - tt_um_rebeccargb_hardware_utf8
          - tt_um_rebeccargb_intercal_alu
          - tt_um_rebeccargb_styler
          - tt_um_rebeccargb_tt09ball_gdsart
          - tt_um_rebeccargb_tt09ball_screensaver
          - tt_um_rebeccargb_universal_decoder
          - tt_um_rebeccargb_vga_pride
          - tt_um_rebeccargb_vga_timing_experiments
          #- tt_um_rebelmike_incrementer # skip: analog
          #- tt_um_rebelmike_register # skip: analog
          - tt_um_regfield
          - tt_um_rejunity_atari2600
          - tt_um_rejunity_lgn_mnist
          - tt_um_resfuzzy
          - tt_um_richardgonzalez_ped_traff_light
          - tt_um_robot_controller_top_module
          - tt_um_rom_vga_screensaver
          - tt_um_romless_cordic_engine
          - tt_um_sc_bipolar_qif_neuron
          - tt_um_semaforo
          - tt_um_serdes
          - tt_um_sha256_processor_dvirdc
          - tt_um_shuangyu_top
          - tt_um_simonsays
          - tt_um_sjsu
          - tt_um_sjsu_vga_music
          - tt_um_sky1
          - tt_um_sleepwell
          - tt_um_snn
          - tt_um_snn_core
          - tt_um_sortaALUAriaMitra
          - tt_um_spacewar
          - tt_um_spi2ws2811x16
          - tt_um_stochastic_addmultiply_CL123abc
          - tt_um_stochastic_integrator_tt9_CL123abc
          - tt_um_stopwatchtop
          - tt_um_stress_sensor
          #- tt_um_subdiduntil2_mixed_signal_classifier # skip: analog
          - tt_um_swangust
          - tt_um_swangust2
          - tt_um_swangust3
          - tt_um_tc503_countdown_timer
          - tt_um_td4
          - tt_um_tdctest_container
          - tt_um_tgrillz_sixSidedDie
          - tt_um_thexeno_rgbw_controller
          #- tt_um_tiny_pll # skip: analog
          - tt_um_tinytapeout_logo_screensaver
          #- tt_um_tnt_mosbius # skip: analog
          #- tt_um_tnt_rf_test # skip: analog
          #- tt_um_tnt_rom_nolvt_test # skip: analog
          #- tt_um_tnt_rom_test # skip: analog
          - tt_um_tobi_mckellar_top
          - tt_um_toivoh_pwl_synth
          - tt_um_top_layer
          - tt_um_torurstrom_async_lock
          - tt_um_tpu
          - tt_um_tqv_peripheral_harness
          - tt_um_trivium_stream_processor
          - tt_um_tt_tinyQV
          - tt_um_tt_tinyQVb
          - tt_um_tv_b_gone
          - tt_um_tv_b_gone_rom
          - tt_um_tx_fsm
          - tt_um_uart
          - tt_um_uart_spi
          #- tt_um_upalermo_simple_analog_circuit # skip: analog
          - tt_um_updown_counter
          #- tt_um_urish_charge_pump # skip: analog
          - tt_um_urish_giant_ringosc
          - tt_um_urish_sic1
          - tt_um_urish_simon
          - tt_um_uwasic_dinogame
          - tt_um_vedic_4x4
          - tt_um_vga_clock
          - tt_um_vga_example
          - tt_um_vga_glyph_mode
          - tt_um_vga_hello_world
          - tt_um_virantha_enigma
          - tt_um_voting_machine
          - tt_um_weighted_majority
          - tt_um_will_keen_solitaire
          - tt_um_wokwi_412635532198550529
          - tt_um_wokwi_414120207283716097
          - tt_um_wokwi_414123795172381697
          - tt_um_wokwi_438920793944579073
          - tt_um_wokwi_440004235377529857
          - tt_um_wokwi_441378095886546945
          - tt_um_wokwi_441382314812372993
          - tt_um_wokwi_441564414591667201
          - tt_um_wokwi_441835796137492481
          - tt_um_wokwi_442131619043064833
          - tt_um_z2a_rgb_mixer

    runs-on: ubuntu-latest
    env:
      OPENLANE_TAG: ${{ github.event.inputs.openlane_tag || '2.2.9' }}
      PDK_ROOT: /home/runner/.volare
      PDK: sky130A

      # Tool versions:
      MAGIC_VERSION: 8.3.552
      KLAYOUT_VERSION: 0.29.12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v4
        with:
          repository: tinytapeout/tt-support-tools
          path: ${{ matrix.project }}/tt
          ref: ttsky25a

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ${{ matrix.project }}
        run: |
          pip install -r tt/requirements.txt

      - name: Install OpenLane ${{ env.OPENLANE_TAG }}
        run: |
          pip install openlane==$OPENLANE_TAG

      - name: Make GDS with OpenLane
        working-directory: ${{ matrix.project }}
        run: |
          git init
          # tt_tool requires a remote to be set, and some commit to be present
          git remote add origin https://github.com/TinyTapeout/dummy
          git config user.email "bot@github.com"
          git config user.name "Tiny Tapeout Bot"
          git commit --allow-empty -m "Dummy commit"

          python tt/tt_tool.py --create-user-config --harden --openlane2

          # Fail if the final GDS file doesn't exist
          if [ ! -f "runs/wokwi/final/gds/${{ matrix.project }}.gds" ]; then
            exit 1
          fi

          # Fail is error.log isn't empty
          if [ -s "runs/wokwi/error.log" ]; then
            exit 1
          fi

          export PDK_VERSION=$(cat runs/wokwi/PDK_SOURCES | awk '{print $2}')
          echo "PDK_VERSION=$PDK_VERSION" >> $GITHUB_ENV

      - name: Set up PDK ${{ env.PDK_VERSION }}
        working-directory: ${{ matrix.project }}
        run: |
          volare enable $PDK_VERSION

      - name: Install magic-vlsi
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential git csh libcairo2-dev tcl-dev tk-dev
          git clone --branch ${MAGIC_VERSION} https://github.com/RTimothyEdwards/magic
          cd magic && ./configure --with-cairo=no --disable-readline --without-x && make && sudo make install

      - name: Install klayout
        run: |
          wget https://github.com/TinyTapeout/klayout/releases/download/v${KLAYOUT_VERSION}/klayout_${KLAYOUT_VERSION}-1_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./klayout_${KLAYOUT_VERSION}-1_amd64.deb

      - name: Run Tiny Tapeout prechecks
        working-directory: ${{ matrix.project }}/tt/precheck
        run: |
          set -o pipefail
          pip install -r requirements.txt
          cp $LEF `dirname $GDS`
          cp $GL `dirname $GDS`/${{ matrix.project }}.v
          python precheck.py --gds $GDS 
          cp -R reports ${PROJECT_DIR}/precheck
          cat reports/results.md | tee -a $GITHUB_STEP_SUMMARY
        env:
          PROJECT_DIR: ${{ github.workspace }}/${{ matrix.project }}
          GDS: ${{ github.workspace }}/${{ matrix.project }}/runs/wokwi/final/gds/${{ matrix.project }}.gds
          LEF: ${{ github.workspace }}/${{ matrix.project }}/runs/wokwi/final/lef/${{ matrix.project }}.lef
          GL: ${{ github.workspace }}/${{ matrix.project }}/runs/wokwi/final/pnl/${{ matrix.project }}.pnl.v

      - name: Publish build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: GDS_${{ matrix.project }}
          path: |
            ${{ matrix.project }}/runs/*
            ${{ matrix.project }}/tt/precheck/*
